name: Testing and Linter
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: development
      USER_ID: 1001
      APP_PORT: 5000
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build --build-arg ENVIRONMENT=${ENVIRONMENT} --build-arg USER_ID=${USER_ID} -t bluehealth-api .
      - name: Lint
        run: docker run --rm bluehealth-api blue --check . --diff
      - name: Test
        run: docker run --rm bluehealth-api pytest --cov bluehealth
